# Generated by Django 5.1.7 on 2025-03-22 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.CharField(blank=True, max_length=100, null=True)),
                ('incident_description', models.TextField(blank=True, null=True)),
                ('vehicle_details', models.TextField(blank=True, null=True)),
                ('damage_description', models.TextField(blank=True, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_info', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('other_parties', models.TextField(blank=True, null=True)),
                ('police_report', models.TextField(blank=True, null=True)),
                ('witnesses', models.TextField(blank=True, null=True)),
                (
                    'conversation',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='claim_information',
                        to='claims_bot.conversation',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='claim_documents/')),
                (
                    'document_type',
                    models.CharField(
                        choices=[
                            ('photos', 'Photos'),
                            ('police_report', 'Police Report'),
                            ('repair_estimate', 'Repair Estimate'),
                            ('driver_license', 'Driver License'),
                            ('other', 'Other'),
                        ],
                        max_length=20,
                    ),
                ),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                (
                    'conversation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='documents',
                        to='claims_bot.conversation',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'response_type',
                    models.CharField(choices=[('text', 'Text'), ('file', 'File')], default='text', max_length=10),
                ),
                ('information_key', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'conversation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='messages',
                        to='claims_bot.conversation',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                (
                    'message',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='claims_bot.message'
                    ),
                ),
            ],
        ),
    ]
