# Generated by Django 5.1.7 on 2025-03-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('claims_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claiminformation',
            name='fraud_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claiminformation',
            name='fraud_reasons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claiminformation',
            name='fraud_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='ClaimDocument',
        ),
    ]
